# Generated by Django 3.0.3 on 2020-04-25 12:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_pic', models.ImageField(upload_to='cat_images/')),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('price', models.IntegerField()),
                ('ord_time', models.DateTimeField(auto_now_add=True)),
                ('exp_ship_time', models.DateField(default=datetime.datetime(2020, 5, 2, 18, 24, 43, 828548))),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('brand_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Brands')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('type_pic', models.ImageField(upload_to='type_images/')),
                ('cat_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Categories')),
            ],
            options={
                'db_table': 'Types',
            },
        ),
        migrations.CreateModel(
            name='TempStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_quant', models.IntegerField()),
                ('product_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Products')),
            ],
            options={
                'db_table': 'TempStock',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_status', models.CharField(choices=[('y', 'Yes'), ('y', 'No')], max_length=10)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Orders')),
            ],
            options={
                'db_table': 'Shipping',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=500)),
                ('product_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Products')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Reviews',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='type_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Types'),
        ),
        migrations.AddField(
            model_name='orders',
            name='product_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('product_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Products')),
            ],
            options={
                'db_table': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
                ('price', models.IntegerField()),
                ('product_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Products')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='ActualStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_quant', models.IntegerField()),
                ('product_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Products')),
            ],
            options={
                'db_table': 'ActualStock',
            },
        ),
    ]
