# Generated by Django 3.0.3 on 2020-04-26 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0003_auto_20200426_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='exp_ship_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 3, 15, 6, 26, 186162)),
        ),
    ]
