# Generated by Django 3.0.3 on 2020-04-27 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0005_auto_20200426_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='exp_ship_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 15, 40, 57, 882784)),
        ),
    ]
