# Generated by Django 3.0.3 on 2020-04-28 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0006_auto_20200427_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='main_img',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='exp_ship_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 16, 25, 37, 356723)),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipping_status',
            field=models.CharField(choices=[('Y', 'YES'), ('Y', 'NO')], default='N', max_length=10),
        ),
    ]
