# Generated by Django 3.0.3 on 2020-04-29 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0007_auto_20200428_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='exp_ship_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 6, 15, 25, 41, 954439)),
        ),
    ]
