# Generated by Django 3.0.3 on 2020-05-02 07:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0009_auto_20200501_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='exp_ship_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 9, 13, 25, 30, 583479)),
        ),
        migrations.CreateModel(
            name='OrderAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Addresses')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Orders')),
            ],
            options={
                'db_table': 'OrderAddresses',
            },
        ),
    ]
