# Generated by Django 3.0.3 on 2020-05-02 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0010_auto_20200502_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='exp_ship_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 9, 14, 13, 1, 288278)),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipping_status',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=10),
        ),
    ]
