# Generated by Django 3.0.3 on 2020-05-02 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0011_auto_20200502_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='exp_ship_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 9, 16, 3, 5, 410408)),
        ),
    ]
