# Generated by Django 3.0.3 on 2020-05-05 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0012_auto_20200502_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='exp_ship_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 12, 16, 26, 29, 392749)),
        ),
    ]
