# Generated by Django 3.0.3 on 2020-05-24 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0013_auto_20200505_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='exp_ship_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 31, 16, 26, 36, 263828)),
        ),
    ]
