# Generated by Django 3.0.3 on 2020-05-30 13:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0014_auto_20200524_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='exp_ship_time',
            field=models.DateField(default=datetime.datetime(2020, 6, 6, 18, 52, 30, 935836)),
        ),
        migrations.CreateModel(
            name='Highlighted_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Products')),
            ],
            options={
                'db_table': 'Highlighted_Products',
            },
        ),
    ]
