# Generated by Django 3.0.3 on 2020-05-30 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0015_auto_20200530_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='exp_ship_time',
            field=models.DateField(default=datetime.datetime(2020, 6, 6, 18, 55, 57, 720973)),
        ),
    ]
