# Generated by Django 3.0.3 on 2020-06-07 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0016_auto_20200530_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='exp_ship_time',
            field=models.DateField(default=datetime.datetime(2020, 6, 14, 15, 3, 6, 481828)),
        ),
    ]
