# Generated by Django 3.0.3 on 2020-06-07 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0017_auto_20200607_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlighted_products',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='exp_ship_time',
            field=models.DateField(default=datetime.datetime(2020, 6, 14, 15, 34, 47, 950869)),
        ),
    ]
