# Generated by Django 4.0.2 on 2022-03-18 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0018_auto_20200607_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='exp_ship_time',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 18, 26, 51, 124224)),
        ),
    ]
