# Generated by Django 3.0.3 on 2020-03-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('chk_password', models.CharField(max_length=20)),
            ],
        ),
    ]
