# Generated by Django 3.0.3 on 2020-03-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0002_auto_20200326_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='chk_password',
        ),
    ]
