# Generated by Django 3.0.3 on 2020-03-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0003_remove_profile_chk_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.IntegerField(max_length=20),
        ),
    ]
