# Generated by Django 3.0.3 on 2020-03-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0004_auto_20200326_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='number',
            new_name='phone',
        ),
    ]
