# Generated by Django 3.0.3 on 2020-04-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0005_auto_20200326_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
