# Generated by Django 3.0.3 on 2020-04-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ekart_app', '0006_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
    ]
