# Generated by Django 3.0.3 on 2020-04-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0007_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pid', models.IntegerField()),
            ],
        ),
    ]
