# Generated by Django 3.0.3 on 2020-04-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0008_rtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
