# Generated by Django 3.0.3 on 2020-04-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
