# Generated by Django 3.0.3 on 2020-04-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0012_auto_20200421_1733'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='Cart2',
        ),
    ]
