# Generated by Django 3.0.3 on 2020-04-21 12:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ekart_app', '0015_auto_20200421_1744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Cart2',
        ),
        migrations.AlterModelTable(
            name='cart2',
            table='Cart2',
        ),
    ]
