# Generated by Django 3.0.3 on 2020-04-21 12:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ekart_app', '0016_auto_20200421_1804'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart2',
            new_name='Cart',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
    ]
