# Generated by Django 3.0.3 on 2020-04-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0017_auto_20200421_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
