# Generated by Django 3.0.3 on 2020-04-25 09:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ekart_app', '0019_cart2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_quant', models.IntegerField()),
            ],
            options={
                'db_table': 'ActualStock',
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_pic', models.ImageField(upload_to='cat_images/')),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product_images/')),
            ],
            options={
                'db_table': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('price', models.IntegerField()),
                ('ord_time', models.DateTimeField(auto_now_add=True)),
                ('exp_ship_time', models.DateField(default=datetime.datetime(2020, 5, 2, 14, 34, 28, 879474))),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_status', models.CharField(choices=[('y', 'Yes'), ('y', 'No')], max_length=10)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Orders')),
            ],
            options={
                'db_table': 'Shipping',
            },
        ),
        migrations.CreateModel(
            name='TempStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_quant', models.IntegerField()),
            ],
            options={
                'db_table': 'TempStock',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('type_pic', models.ImageField(upload_to='type_images/')),
                ('cat_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Categories')),
            ],
            options={
                'db_table': 'Types',
            },
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='cart2',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='cart2',
            name='uid',
        ),
        migrations.DeleteModel(
            name='Rtable',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='tag',
        ),
        migrations.AlterModelTable(
            name='products',
            table='Products',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Cart2',
        ),
        migrations.AddField(
            model_name='tempstock',
            name='product_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Products'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='product_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Products'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='product_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='images',
            name='product_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Products'),
        ),
        migrations.AddField(
            model_name='carts',
            name='product_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Products'),
        ),
        migrations.AddField(
            model_name='carts',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actualstock',
            name='product_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Products'),
        ),
        migrations.AddField(
            model_name='products',
            name='brand_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Brands'),
        ),
        migrations.AddField(
            model_name='products',
            name='type_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Types'),
        ),
    ]
