# Generated by Django 3.0.3 on 2020-04-25 09:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0020_auto_20200425_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='exp_ship_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 2, 14, 37, 55, 660769)),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Brands'),
        ),
        migrations.AlterField(
            model_name='products',
            name='type_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekart_app.Types'),
        ),
    ]
