# Generated by Django 3.0.3 on 2020-04-25 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0023_auto_20200425_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='exp_ship_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 2, 14, 38, 14, 365802)),
        ),
    ]
