# Generated by Django 3.0.3 on 2020-04-25 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart_app', '0027_auto_20200425_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='exp_ship_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 2, 15, 3, 2, 83910)),
        ),
    ]
